### PR TITLE
Update procfile

### PR DESCRIPTION
**Pull request by osadolortech**

### CODE REVIEW

**Review by iamr0b0tx — APPROVED** [review]
Nice work. but where are all the other changes or is this the start of your work?

**Comment by osadolortech** [comment]
No sir I have done all 5 methods actually, but I was really struggling with
the git, I just got a hold on it now

**Comment by iamr0b0tx** [comment]
This means you have to start again because I can't review all that work without a PR. tell the others

**Comment by osadolortech** [comment]
Ok, I will do that.

**Pull request merged**
